
// <auto-generated />

using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using System;

namespace CovidInformer.Core.Db.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20220218084909_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.22");

            modelBuilder.Entity("CovidInformer.Core.Db.Models.Counter", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("INTEGER");

                    b.Property<long>("CountryId")
                        .HasColumnName("CountryRef")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdateId")
                        .HasColumnName("UpdateRef")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("Value")
                        .HasColumnName("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("UpdateId");

                    b.ToTable("Counter");
                });

            modelBuilder.Entity("CovidInformer.Core.Db.Models.Country", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnName("DisplayName")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.HasIndex("DisplayName")
                        .IsUnique();

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Country");
                });

            modelBuilder.Entity("CovidInformer.Core.Db.Models.Update", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Updated")
                        .HasColumnName("Updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Updated");

                    b.ToTable("Update");
                });

            modelBuilder.Entity("CovidInformer.Core.Db.Models.Counter", b =>
                {
                    b.HasOne("CovidInformer.Core.Db.Models.Country", "Country")
                        .WithMany("Counters")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CovidInformer.Core.Db.Models.Update", "Update")
                        .WithMany("Counters")
                        .HasForeignKey("UpdateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
